version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: US/Pacific
  open-pull-requests-limit: 99
  reviewers:
  - airsquared
  assignees:
  - airsquared
