name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked stale because it has been open 20 days with no activity. If you would like this to remain open, please remove the stale label or comment, otherwise this issue will be closed in 3 days.'
        days-before-stale: 20
        days-before-close: 3
        exempt-issue-labels: 'enhancement'
